#!/bin/sh

print_volume() {
	volume="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
	if test "$volume" -gt 0
	then
		echo " ${volume}%"
	else
		echo " 0%"
	fi
}

print_wifi() {
    grep "^\s*w" /proc/net/wireless | awk '{ print "" }'
    sed "s/down//;s/up//" /sys/class/net/e*/operstate
}

print_bat() {
	hash acpi || return 0
	onl="$(grep "on-line" < acpi -V)"
	charge="$(awk '{ sum += $1 } END { print sum }' /sys/class/power_supply/BAT*/capacity)"
	if test -z "$onl"
	then
		echo "${charge}"
	else
		echo "${charge}"
	fi
}

print_date() {
	date "+%a %m / %d / %y ][  %I:%M %p ]"
}

print_cpu() {
	temp="$(awk '{ cpu1=$1/1000;cpu2=$2/1000; } END { print "CPU1: ", cpu1, " ", "CPU2: ", cpu2 }' /sys/class/thermal/thermal_zone*/temp)"
	echo "${temp}"
}

while true
do
    #xsetroot -name "[ $(print_wifi) ][ $(print_volume) ][  $(print_bat)% ][  $(print_date)"
    #xsetroot -name "[ $(print_cpu) ][  $(print_bat)% ][  $(print_date)"
    xsetroot -name "[  $(print_bat)% ][  $(print_date)"
	sleep 1m
done
